### ISSUE TITLE
issue: when it will reach version 1 or some recommended stable version

### ISSUE THREAD

**Issue by zaxebo1** [asciiascetic/hatch#1]
You have done excellent work.  Kudos :+1: 
You are saying that "This is mega-ultra-alpha version stuff here. "
So, My only issue/curiosity is that when it will reach version 1.0 or some stable recommended version?

**Comment by zaxebo1** [comment]
For your references of earlier efforts on implementing lisp in haxe:

effort1)   http://web.archive.org/web/20130508000712/http://www.profound7.com/blog/orbit/introducing-orbit-the-awesome-mix-of-lisp-lua-and-javascript/
              https://github.com/0b1kn00b/Orbit

effort 2) https://github.com/zick/HaxeLisp

**Comment by asciiascetic** [comment]
Hey thanks for your interest in this beautiful but recently neglected idea.  If you're keen on a finished and stable project, then I can formalize a roadmap in the coming days.  

One issue is that I experimented with Haskell-esque IO and Haxe interop, but am dissatisfied with that approach. I need to step back and re-write interop to work the way it does on the web REPL example.  I think hitting that kink stalled my effort a litle.

Anyway. I'll update the README with a development roadmap this week :)

**Comment by accidentalrebel** [comment]
I look forward to the roadmap. Goodluck on the project!

**Comment by asciiascetic** [comment]
https://github.com/asciiascetic/hatch/blob/master/README.md 

@zaxebo1 So in answer to your initial question, I think I will try to finish one of these bullet points each weekend over the following several weekends.  So we're looking at around 2 months for a 0.9.0 beta.  

After that I'd hope to use it in a real project or two, do some bugfixes, see what features aren't working, and then after fixing them shoot for a 1.0.0.  Cheers and thanks for the encouragement!

**Comment by zaxebo1** [comment]
great roadmap. 
Only one thing, "After" you finish the things in this roadmap, you may also include one writeup on the internal architecture of the hatch(and how to customize it), so that after it reaches 1.0.0, whoever wants to contribute to it, can easily jumpstart with less barrier to the development contribution

**Comment by asciiascetic** [comment]
@zaxebo1 Thats a great idea, I think I will.
